### ISSUE TITLE
静态资源问题

### ISSUE THREAD

**Issue by lyxlucky** [DlaoAyu/parking-admin#1]
您好，车牌的静态资源貌似不是很齐全，希望能补齐一下
![image](https://github.com/DlaoAyu/parking-admin/assets/59909125/a74bb4c0-9468-4630-8d41-2c81a3c460f5)

ps：已star

**Comment by DlaoAyu** [comment]
这是前端上传图片存储到硬盘的地址，资源可以自己重新找，重新上传
