### ISSUE TITLE
很多逻辑bug

### ISSUE THREAD

**Issue by lyxlucky** [DlaoAyu/parking-admin#2]
1. 停车场管理下的模糊查询用不了，因为sql完全没加参数
![image](https://github.com/DlaoAyu/parking-admin/assets/59909125/40ac6ffb-0a59-44e8-a8da-db3fbb235036)
2.停车场管理下新增的停车场不会显示，因为查询是多表查询，但是插入却是单表插入。

!!!!!下面是我修改过后的代码
主要修改功能：
1.停车场管理下的模糊查询
2.修改文件上传路径
3.新增的停车场会显示
[parking-admin.zip](https://github.com/DlaoAyu/parking-admin/files/13446871/parking-admin.zip)

**Comment by DlaoAyu** [comment]
1、确实缺少对应的SQL
3、新增停车场需要在用户管理中选择才能展示

**Comment by lyxlucky** [comment]
好吧，确实有点没想到，有点违背常理

**Comment by lyxlucky** [comment]
对了，首页显示数量有问题，默认显示的是所有的停车场数量，即你没勾选也会算上

**Comment by DlaoAyu** [comment]
这些问题你自己解决吧，这个时间太长，我已经没时间再去优化这些东西了

**Comment by lyxlucky** [comment]
我自己都解决了，我只是回来告诉你而已
